name: cv
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=1
- jpeg=8d=0
- libgfortran=3.0.0=1
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.3=0
- numpy=1.10.4=py27_2
- opencv=2.4.10=np110py27_1
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_2
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- qt=4.8.7=2
- readline=6.2=2
- scikit-learn=0.17.1=np110py27_1
- scipy=0.17.1=np110py27_0
- setuptools=22.0.5=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - arrow==0.7.0
  - atomicwrites==1.0.0
  - b2==0.5.2
  - binaryornot==0.4.0
  - bioblend==0.7.0
  - boto==2.39.0
  - bugwarrior==1.4.0
  - cached-property==1.3.0
  - chardet==2.3.0
  - click==6.6
  - click-log==0.1.3
  - click-threading==0.1.2
  - colorama==0.3.7
  - configobj==5.0.6
  - contextlib2==0.5.1
  - cookiecutter==1.4.0
  - cptids==0.1.0
  - crossmap==0.2.2
  - cython==0.23.4
  - django==1.9.4
  - django-haystack==2.4.1
  - docker-compose==1.6.2
  - docker-py==1.7.2
  - dockerpty==0.4.1
  - docopt==0.6.2
  - docutils==0.12
  - dogpile.cache==0.5.7
  - dogpile.core==0.4.1
  - fake-factory==0.5.7
  - flake8==2.5.4
  - functools32==3.2.3.post2
  - future==0.15.2
  - futures==3.0.5
  - galaxy-lib==16.4.0
  - glob2==0.4.1
  - hashids==1.1.0
  - haxor-news==0.3.1
  - icalendar==3.9.2
  - ipaddress==1.0.16
  - jinja2==2.8
  - jinja2-time==0.1.0
  - jsonschema==2.5.1
  - keyring==8.7
  - keyrings.alt==1.1.1
  - khal==0.8.1
  - lockfile==0.12.2
  - lxml==3.6.0
  - markupsafe==0.23
  - mccabe==0.4.0
  - offtrac==0.1.0
  - pep8==1.7.0
  - planemo==0.23.0
  - portalocker==0.5.7
  - poyo==0.2.0
  - prompt-toolkit==0.52
  - proselint==0.4.0
  - pyflakes==1.0.0
  - pygithub3==0.5.1
  - pygments==2.1.3
  - python-bugzilla==1.2.2
  - pyxdg==0.25
  - pyyaml==3.11
  - raven==5.11.1
  - requests==2.7.0
  - requests-toolbelt==0.6.0
  - taskw==1.1.0
  - taskwarrior-inthe.am==0.1.1
  - texttable==0.8.4
  - twiggy==0.4.7
  - tzlocal==1.2.2
  - urwid==1.3.1
  - vdirsyncer==0.9.3
  - virtualenv==15.0.0
  - wcwidth==0.1.6
  - websocket-client==0.35.0
  - whichcraft==0.1.1

